version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=btredb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python3 manage.py runserver"
    volumes:
      - .:/pages
    ports:
      - "8000:8000"
    depends_on:
      - db
